/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GovernorContract__factory } from "./GovernorContract__factory";
export { MyGovernor__factory } from "./MyGovernor__factory";
